branch-defaults:
  default:
    environment: udagram-prakash-dev-dev
    group_suffix: null
deploy:
  artifact: ./www/Archive.zip
global:
  application_name: udagram-prakash-dev
  branch: null
  default_ec2_keyname: udagram-eb-keypair
  default_platform: Node.js
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
